export enum ActionTypes {
  GET_ALL = 'GET_ALL',
  STORE_TRANSACTION = 'STORE_TRANSACTION',
  GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES',
  PICK_ACCOUNT = 'PICK_ACCOUNT',
  GET_ALL_TRANSACTIONS = 'GET_ALL_TRANSACTIONS'
}
