export enum GetterTypes {
	ACCOUNTS = 'ACCOUNTS',
	ACCOUNT_SELECTED = 'ACCOUNT_SELECTED',
	CATEGORIES = 'CATEGORIES',
	CATEGORIES_OPTIONS = 'CATEGORIES_OPTIONS',
	CATEGORY_SELECTED = 'CATEGORY_SELECTED',
	CATEGORIES_ALLOWED = 'CATEGORIES_ALLOWED',
	CATEGORIES_DEFAULT_ALLOWED = 'CATEGORIES_DEFAULT_ALLOWED',
	TRANSACTIONS = 'TRANSACTIONS',
	TRANSACTION_STATUS = 'TRANSACTION_STATUS'
}
