export enum MutationTypes {
	SET_ACCOUNTS = 'SET_ACCOUNTS',
	PICK_ACCOUNT = 'PICK_ACCOUNT',
	SET_CATEGORIES = 'SET_CATEGORIES',
	PICK_CATEGORY = 'PICK_CATEGORY',
	CLEAN_CATEGORY_SELECTED = 'CLEAN_CATEGORY_SELECTED',
	SET_TRANSACTIONS = 'SET_TRANSACTIONS',
	SET_CATEGORIES_ALLOWED = 'SET_CATEGORIES_ALLOWED',
	CHANGE_TRANSACTION_STATUS = 'CHANGE_TRANSACTION_STATUS'
}
